### ISSUE TITLE
main.js:52291 Error: Uncaught (in promise): TypeError: manateeScanner.scanner.setCallback is not a function

### ISSUE THREAD

**Issue by bhupathibhargva** [manateeworks/manateeworks-barcodescanner-ionic-starter#1]
im getting the following error when i try to run the ionic 2 demo app..

Uncaught (in promise): Type Error: manateeScanner.scanner.setCallback is not a function in console
mwbScanner not available @12343224543 when click in scan button.
EXCEPTION: Uncaught (in promise): ReferenceError: mwbScanner is not defined
ReferenceError: mwbScanner is not defined
at ManateeScanner.config (file:///android_asset/www/build/main.js:38229:21)
at file:///android_asset/www/build/main.js:99432:28
at t.invoke (file:///android_asset/www/build/polyfills.js:3:9094)
at Object.onInvoke (file:///android_asset/www/build/main.js:35929:37)
at t.invoke (file:///android_asset/www/build/polyfills.js:3:9045)
at e.run (file:///android_asset/www/build/polyfills.js:3:6481)
at file:///android_asset/www/build/polyfills.js:3:4583
at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9723)
at Object.onInvokeTask (file:///android_asset/www/build/main.js:35920:37)
at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9659)
ErrorHandler.handleError @ main.js:52288
main.js:52293 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ main.js:52293

and mwbScanner not defined when i try to run the ionic 2 starter application

please help me understand what i am doing wrong

**Comment by manateeworks** [comment]
Hi @bhupathibhargva ,

there have been some changes with the latest Ionic version, please use the updated content and installation guide for the [Ioinic 2 Demo App with Manatee Works Barcode Scanner](https://github.com/manateeworks/manateeworks-barcodescanner-ionic-starter#installation)

Best regards,
Team Manatee
